apiVersion: v1
kind: Service
metadata:
  name: indexer-agent
spec:
  type: NodePort
  selector:
    app: indexer-agent
  ports:
    - name: syncing
      protocol: TCP
      port: 8002
      targetPort: 8002
